In [5]:
import gym
import numpy as np
import matplotlib.pyplot as plt
import json
import argparse
import RLAlgs
import RLModels
import core
import copy
import os
import time

import CustomEnvs

convN = 100
alpha = 0.1
discount = 0.6
epsilon = 1
fedP = 10
syncBackups = 100 * convN
stochasticPolicy = True
envSeed = 3701
trial = 0

startTime = 0
totalTime = 3 * 60 * 60
totalTime -= 600

states = 4
actions = 3

jsonFilePrefix = "mdpv4_"
# dirPath = "~/scratch/RL"
dirPath = "/storage/home/hcoda1/2/meinhorn6/scratch/RL"
jsonDict = {}

windows = False
if os.name == 'nt':
    windows = True
    dirPath = "C:/Users/Michael Einhorn/Documents/GTML/RL"

In [13]:
def benchBell():
    envBell = CustomEnvs.RandomMDP(states, actions, seed=envSeed)

    print(envBell.transMat)
    print(envBell.rewardMat)

    modelBell = RLModels.QTabular(envBell, stochasticPolicy=True)
    model = copy.deepcopy(modelBell)
    modelBell = RLAlgs.QLearningTabularBellman(model=modelBell, env=envBell, gamma=discount, iterN=10000)
    
    scoreBell, sList = RLAlgs.score(env=envBell, model=modelBell, epLimit=10000, iterN=1, printErr=False)

    modelRand = RLModels.RandomPolicy(envBell)
    scoreRand, sListRand = RLAlgs.score(env=envBell, model=modelRand, epLimit=10000, iterN=1, printErr=False)
    print("bellman vs random")
    print(scoreBell)
    print(scoreRand)
    print("ratio")
    print(scoreBell / scoreRand)
    print("distance")
    print(model.diff(modelBell))

In [14]:
benchBell()

[[[4.29939900e-01 1.77871993e-01 1.96554645e-01 1.95633462e-01]
  [2.32958155e-01 2.32958119e-01 3.01125610e-01 2.32958116e-01]
  [3.31306128e-26 3.34014303e-01 3.32992802e-01 3.32992895e-01]]

 [[1.28653130e-01 1.28650753e-01 1.28650753e-01 6.14045363e-01]
  [3.33475528e-01 3.33515479e-01 1.38269912e-07 3.33008855e-01]
  [0.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00]]

 [[1.00000000e+00 1.57813896e-10 1.21738303e-10 1.21711074e-10]
  [3.74112621e-01 2.51745269e-01 3.74142110e-01 0.00000000e+00]
  [1.00000000e+00 8.71486596e-74 8.71486668e-74 0.00000000e+00]]

 [[4.56766321e-08 9.99999906e-01 0.00000000e+00 4.79458771e-08]
  [5.95334276e-12 1.00000000e+00 1.04743474e-12 7.18298397e-11]
  [3.35126712e-01 3.28768090e-01 9.78502254e-04 3.35126696e-01]]]
[-0.81671681  1.46971386  0.44813686 -0.77318491]
bellman vs random
2069.669167296298
1232.706751203575
ratio
1.6789631153358573
distance
3.7055958469869537
